<?php 

$projectCategory = ['commercial'=> 'Commericial', 'hospitality'=>'Hospitality','institutional'=>'Institutional','residential'=> 'Residential'];
$picConfig = [
    'commercial' => [
        'cafe'=> [
            'images' => [1,2,3,4,5,6],
            'description' => 'This gives the description of the cafe',
            'title'=> 'Kannans Cafe',
            'area'=> '2852',
            'id'=>1,
            'start_date'=> '12 Apr 2020',
            'location'=> 'Vellore',
            'client'=> 'Avinash',
            'plan_description'=>'We have handled the project in an excellent way',
        ],
        'car_spa'=> [
            'images' => [1],
            'description' => 'This gives the description of the car spa',
            'title'=> 'Car spa',
            'area'=> '2852',
            'id'=>2,
            'start_date'=> '12 Apr 2020',
            'location'=> 'Vellore',
            'client'=> 'Avinash',
            'plan_description'=>'We have handled the project in an excellent way',
        ],
        'chennai_silks'=> [
            'images' => [1],
            'description' => 'This gives the description of the chennai silks',
            'title'=> 'Chennai silks',
            'area'=> '2852',
            'id'=>3,
            'start_date'=> '12 Apr 2020',
            'location'=> 'Vellore',
            'client'=> 'Avinash',
            'plan_description'=>'We have handled the project in an excellent way',
        ],
        'geetha_timber'=> [
            'images' => [1,2],
            'description' => 'This gives the description of the geetha timbers',
            'title'=> 'Geetha timbers',
            'area'=> '2852',
            'id'=>4,
            'start_date'=> '12 Apr 2020',
            'location'=> 'Vellore',
            'client'=> 'Avinash',
            'plan_description'=>'We have handled the project in an excellent way',
        ],
        'lorry_office'=> [
            'images' => [1,2,3],
            'description' => 'This gives the description of the lorry office',
            'title'=> 'Lorry office',
            'area'=> '2852',
            'id'=>5,
            'start_date'=> '12 Apr 2020',
            'location'=> 'Vellore',
            'client'=> 'Avinash',
            'plan_description'=>'We have handled the project in an excellent way',
        ],
        'ospray'=> [
            'images' => [1,2,3,4,5],
            'description' => 'This gives the description of the ospray',
            'title'=> 'Ospray',
            'area'=> '2852',
            'id'=>6,
            'start_date'=> '12 Apr 2020',
            'location'=> 'Vellore',
            'client'=> 'Avinash',
            'plan_description'=>'We have handled the project in an excellent way',
        ],
        'salon'=> [
            'images' => [1,2,3,4,5,6,7],
            'description' => 'This gives the description of the salon',
            'title'=> 'Salon',
            'area'=> '2852',
            'id'=>7,
            'start_date'=> '12 Apr 2020',
            'location'=> 'Vellore',
            'client'=> 'Avinash',
            'plan_description'=>'We have handled the project in an excellent way',
        ],
        'tvm_mahal'=> [
            'images' => [1,2],
            'description' => 'This gives the description of the mahal',
            'title'=> 'Tvm mahal',
            'area'=> '2852',
            'id'=>8,
            'start_date'=> '12 Apr 2020',
            'location'=> 'Vellore',
            'client'=> 'Avinash',
            'plan_description'=>'We have handled the project in an excellent way',
        ],
        'kv_overseas'=> [
            'images' => [1,2,3,4],
            'description' => 'This gives the description of the overseas office',
            'title'=> 'Overseas office',
            'area'=> '2852',
            'id'=>9,
            'start_date'=> '12 Apr 2020',
            'location'=> 'Vellore',
            'client'=> 'Avinash',
            'plan_description'=>'We have handled the project in an excellent way',
        ],
    ],
    'hospitality'=>[
        'hospital'=> [
            'images' => [1,2,3],
            'description' => 'This gives the description of the hospital',
            'title'=> 'Hospital',
            'area'=> '2852',
            'id'=>10,
            'start_date'=> '12 Apr 2020',
            'location'=> 'Vellore',
            'client'=> 'Avinash',
            'plan_description'=>'We have handled the project in an excellent way',
        ]
    ],
    'institutional'=>[
        'vidhya_school'=> [
            'images' => [1,2],
            'description' => 'This gives the description of the school design',
            'title'=> 'School',
            'area'=> '2852',
            'id'=>11,
            'start_date'=> '12 Apr 2020',
            'location'=> 'Vellore',
            'client'=> 'Avinash',
            'plan_description'=>'We have handled the project in an excellent way',
        ]
    ],
    'residential'=>[
        'basha'=> [
            'images' => [1,2],
            'description' => 'This gives the description of the Basha Residence',
            'title'=> 'Basha Residence',
            'area'=> '2852',
            'id'=>12,
            'start_date'=> '12 Apr 2020',
            'location'=> 'Vellore',
            'client'=> 'Avinash',
            'plan_description'=>'We have handled the project in an excellent way',
        ],
        'durai'=> [
            'images' => [1],
            'description' => 'This gives the description of the Durai Residence',
            'title'=> 'Durai residence',
            'area'=> '2852',
            'id'=>13,
            'start_date'=> '12 Apr 2020',
            'location'=> 'Vellore',
            'client'=> 'Avinash',
            'plan_description'=>'We have handled the project in an excellent way',
        ],
        // 'gowtham_gateways'=> [
        //     'images' => [1,2,3,4,5,6,7,8,9,10],
        //     'description' => 'This gives the description of the Gowtham gateways',
        //     'title'=> 'Gowtham Gateways',
        //     'area'=> '2852',
        //     'id'=>14,
        //     'start_date'=> '12 Apr 2020',
        //     'location'=> 'Vellore',
        //     'client'=> 'Avinash',
        //     'plan_description'=>'We have handled the project in an excellent way',
        // ],
        'imayavaram'=> [
            'images' => [1],
            'description' => 'This gives the description of the imayavaram',
            'title'=> 'Imayavaram Residence',
            'area'=> '2852',
            'id'=>15,
            'start_date'=> '12 Apr 2020',
            'location'=> 'Vellore',
            'client'=> 'Avinash',
            'plan_description'=>'We have handled the project in an excellent way',
        ],
        'rajan_residence'=> [
            'images' => [1,2],
            'description' => 'This gives the description of the rajan residence',
            'title'=> 'Rajan Residence',
            'area'=> '2852',
            'id'=>16,
            'start_date'=> '12 Apr 2020',
            'location'=> 'Vellore',
            'client'=> 'Avinash',
            'plan_description'=>'We have handled the project in an excellent way',
        ],
    ],
];
?>